name: GC_AUTH
runs: 
  using: "composite"
  steps:
  - uses: google-github-actions/setup-gcloud@v0.2.0
    with:
      project_id: ${{ secrets.GC_PROJECT_ID }}
      service_account_key: ${{ secrets.GC_SERVICE_ACCOUNT }}
      service_account_email: ${{ secrets.GC_SERVICE_ACCOUNT_EMAIL }}
  - name: Enable the necessary APIs and enable docker auth
    shell: bash
    run: |-
      gcloud services enable containerregistry.googleapis.com
      gcloud services enable run.googleapis.com
      gcloud --quiet auth configure-docker