name: GC AUTH
env: 
  GC_PROJECT_ID: ${{ secrets.GC_PROJECT_ID }}
  GC_REGION: ${{ secrets.GC_REGION }}

jobs:
  gc_auth:
    name: GC Authentication
    runs-on: ubuntu-latest
    steps:
      # GC 인증
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GC_PROJECT_ID }}
          service_account_key: ${{ secrets.GC_SERVICE_ACCOUNT }}
          service_account_email: ${{ secrets.GC_SERVICE_ACCOUNT_EMAIL }}

      # 도커 사용 설정
      - name: Enable the necessary APIs and enable docker auth
        run: |-
          gcloud services enable containerregistry.googleapis.com
          gcloud services enable run.googleapis.com
          gcloud --quiet auth configure-docker
