name: NX Affected Release
on:
  push:
    branches:
      - master
      - main

env:
  BEFORE_SHA: ${{ github.event.before }}
  # gcr.io 리포 이름

jobs:
  affected_build:
    name: build only affected apps
    runs-on: ubuntu-latest
    steps:
      # GC_AUTH
      - name: GC_AUTH
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GC_PROJECT_ID }}
          service_account_key: ${{ secrets.GC_SERVICE_ACCOUNT }}
          service_account_email: ${{ secrets.GC_SERVICE_ACCOUNT_EMAIL }}

      # 도커 사용 설정
      - name: Enable the necessary APIs and enable docker auth
        run: |-
          gcloud services enable containerregistry.googleapis.com
          gcloud services enable run.googleapis.com
          gcloud --quiet auth configure-docker

      # 변경된 트리만 재빌드 => 배포
      - name: BUILD AFFECTED
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: prod-build


   
