name: NX Affected Release
on:
  push:
    branches:
      - master
      - main

env:
  BEFORE_SHA: ${{ github.event.before }}
  # gcr.io 리포 이름

jobs:
  affected_build:
    name: build only affected apps
    runs-on: ubuntu-latest
    steps:
      # Nx git diff 사용으로 affted 사용을 위한 git history fetching
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: git fetch origin master
      # Nx 사용을 위한 디펜던시 설치
      - name: Install Dependency
        run: npm install

      # GC_AUTH
      - name: GC_AUTH
        uses: ./.github/actions

      # Affected build
      - name: Run Affected Build and Deploy
        shell: bash
        run: npm run affected:prod-build -- --base=$BEFORE_SHA
